services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yakamara\CommonBundle\:
        resource: '../../{EventSubscriber,Form,Twig,Util}'

    Yakamara\CommonBundle\Security\SecurityContext: ~

    Yakamara\CommonBundle\ValueResolver\DateTimeValueResolver:
        tags:
            - { name: controller.argument_value_resolver }
