services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yakamara\CommonBundle\:
        resource: '../../{EventSubscriber,Form,Twig,Util}'

    Yakamara\CommonBundle\Security\SecurityContext: ~

    Yakamara\CommonBundle\Request\DateTimeParamConverter:
        tags:
            - { name: request.param_converter }
