parameters:
    security.access.decision_manager.class: Yakamara\CommonBundle\Security\AccessDecisionManager

services:
    yakamara_common.datetime:
        class: Yakamara\CommonBundle\Util\DateTimeUtil
        arguments: [@translator]
    yakamara_common.security_context:
        class: Yakamara\CommonBundle\Security\SecurityContext
        arguments: [@security.token_storage, @security.authorization_checker]
    yakamara_common.switch_user_checker:
        class: Yakamara\CommonBundle\Security\SwitchUserChecker
        arguments: [@yakamara_common.security_context]
    yakamara_common.form.type.gender:
        class: Yakamara\CommonBundle\Form\Type\GenderType
        tags:
            - { name: form.type, alias: gender }
    yakamara_common.form.extension.label:
        class: Yakamara\CommonBundle\Form\Extension\LabelExtension
        tags:
            - { name: form.type_extension, alias: form }
    yakamara_common.form.extension.date:
        class: Yakamara\CommonBundle\Form\Extension\DateExtension
        tags:
            - { name: form.type_extension, alias: date }
    yakamara_common.form.extension.time:
        class: Yakamara\CommonBundle\Form\Extension\TimeExtension
        tags:
            - { name: form.type_extension, alias: time }
    yakamara_common.form.extension.datetime:
        class: Yakamara\CommonBundle\Form\Extension\DateTimeExtension
        tags:
            - { name: form.type_extension, alias: datetime }
    yakamara_common.form.extension.model:
        class: Yakamara\CommonBundle\Form\Extension\ModelExtension
        tags:
            - { name: form.type_extension, alias: model }
    yakamara_common.twig_extension:
        class: Yakamara\CommonBundle\Twig\Extension
        arguments: [@service_container]
        public: false
        tags:
            - { name: twig.extension }
